import type { Locale } from './model'

/** A skill written the same in every language (a tool), or per resume language. */
type Term = string | Record<Locale, string>

const term = (
  en: string,
  de: string,
  es: string,
  bg: string,
  uk: string,
  ru: string,
): Term => ({
  en,
  de,
  es,
  bg,
  uk,
  ru,
})

const research = term(
    'User research',
    'Nutzerforschung',
    'Investigación de usuarios',
    'Потребителски проучвания',
    'Дослідження користувачів',
    'Исследования пользователей',
  ),
  prototyping = term(
    'Prototyping',
    'Prototyping',
    'Prototipado',
    'Прототипиране',
    'Прототипування',
    'Прототипирование',
  ),
  designSystems = term(
    'Design systems',
    'Designsysteme',
    'Sistemas de diseño',
    'Дизайн системи',
    'Дизайн-системи',
    'Дизайн-системы',
  ),
  usability = term(
    'Usability testing',
    'Usability-Tests',
    'Pruebas de usabilidad',
    'Тестване на използваемостта',
    'Юзабіліті-тестування',
    'Юзабилити-тестирование',
  ),
  wireframes = term(
    'Wireframing',
    'Wireframing',
    'Wireframes',
    'Уайрфрейми',
    'Вайрфрейми',
    'Вайрфреймы',
  ),
  accessibility = term(
    'Accessibility',
    'Barrierefreiheit',
    'Accesibilidad',
    'Достъпност',
    'Доступність',
    'Доступность',
  ),
  testing = term(
    'Automated testing',
    'Automatisierte Tests',
    'Pruebas automatizadas',
    'Автоматизирани тестове',
    'Автоматизоване тестування',
    'Автотесты',
  ),
  statistics = term(
    'Statistics',
    'Statistik',
    'Estadística',
    'Статистика',
    'Статистика',
    'Статистика',
  ),
  dataViz = term(
    'Data visualization',
    'Datenvisualisierung',
    'Visualización de datos',
    'Визуализация на данни',
    'Візуалізація даних',
    'Визуализация данных',
  ),
  ml = term(
    'Machine learning',
    'Maschinelles Lernen',
    'Aprendizaje automático',
    'Машинно обучение',
    'Машинне навчання',
    'Машинное обучение',
  ),
  strategy = term(
    'Product strategy',
    'Produktstrategie',
    'Estrategia de producto',
    'Продуктова стратегия',
    'Продуктова стратегія',
    'Продуктовая стратегия',
  ),
  roadmap = term(
    'Roadmapping',
    'Roadmap-Planung',
    'Hoja de ruta',
    'Пътна карта',
    'Дорожня карта',
    'Дорожная карта',
  ),
  stakeholders = term(
    'Stakeholder management',
    'Stakeholder-Management',
    'Gestión de stakeholders',
    'Управление на заинтересовани страни',
    'Робота зі стейкхолдерами',
    'Работа со стейкхолдерами',
  ),
  prioritization = term(
    'Prioritization',
    'Priorisierung',
    'Priorización',
    'Приоритизиране',
    'Пріоритизація',
    'Приоритизация',
  ),
  analytics = term(
    'Product analytics',
    'Produktanalyse',
    'Analítica de producto',
    'Продуктов анализ',
    'Продуктова аналітика',
    'Продуктовая аналитика',
  ),
  content = term(
    'Content marketing',
    'Content-Marketing',
    'Marketing de contenidos',
    'Контент маркетинг',
    'Контент-маркетинг',
    'Контент-маркетинг',
  ),
  social = term(
    'Social media',
    'Social Media',
    'Redes sociales',
    'Социални мрежи',
    'Соцмережі',
    'Соцсети',
  ),
  emailMarketing = term(
    'Email marketing',
    'E-Mail-Marketing',
    'Email marketing',
    'Имейл маркетинг',
    'Email-маркетинг',
    'Email-маркетинг',
  ),
  copywriting = term(
    'Copywriting',
    'Texterstellung',
    'Redacción publicitaria',
    'Копирайтинг',
    'Копірайтинг',
    'Копирайтинг',
  ),
  automation = term(
    'Marketing automation',
    'Marketing-Automatisierung',
    'Automatización de marketing',
    'Маркетингова автоматизация',
    'Автоматизація маркетингу',
    'Автоматизация маркетинга',
  ),
  leadGen = term(
    'Lead generation',
    'Leadgenerierung',
    'Generación de leads',
    'Генериране на лийдове',
    'Лідогенерація',
    'Лидогенерация',
  ),
  negotiation = term(
    'Negotiation',
    'Verhandlungsführung',
    'Negociación',
    'Преговори',
    'Переговори',
    'Переговоры',
  ),
  accounts = term(
    'Account management',
    'Kundenbetreuung',
    'Gestión de cuentas',
    'Управление на клиенти',
    'Ведення клієнтів',
    'Ведение клиентов',
  ),
  b2b = term(
    'B2B sales',
    'B2B-Vertrieb',
    'Ventas B2B',
    'B2B продажби',
    'B2B-продажі',
    'B2B-продажи',
  ),
  pipeline = term(
    'Pipeline management',
    'Pipeline-Management',
    'Gestión del pipeline',
    'Управление на фунията',
    'Управління воронкою',
    'Управление воронкой',
  ),
  presentations = term(
    'Presentations',
    'Präsentationen',
    'Presentaciones',
    'Презентации',
    'Презентації',
    'Презентации',
  ),
  modeling = term(
    'Financial modeling',
    'Finanzmodellierung',
    'Modelización financiera',
    'Финансово моделиране',
    'Фінансове моделювання',
    'Финансовое моделирование',
  ),
  budgeting = term(
    'Budgeting',
    'Budgetplanung',
    'Presupuestos',
    'Бюджетиране',
    'Бюджетування',
    'Бюджетирование',
  ),
  forecasting = term(
    'Forecasting',
    'Forecasting',
    'Previsión',
    'Прогнозиране',
    'Прогнозування',
    'Прогнозирование',
  ),
  accounting = term(
    'Accounting',
    'Buchhaltung',
    'Contabilidad',
    'Счетоводство',
    'Бухгалтерський облік',
    'Бухгалтерский учёт',
  ),
  reporting = term(
    'Financial reporting',
    'Finanzberichterstattung',
    'Informes financieros',
    'Финансова отчетност',
    'Фінансова звітність',
    'Финансовая отчётность',
  ),
  controlling = term(
    'Controlling',
    'Controlling',
    'Control de gestión',
    'Контролинг',
    'Контролінг',
    'Контроллинг',
  ),
  recruiting = term(
    'Recruiting',
    'Recruiting',
    'Reclutamiento',
    'Подбор на персонал',
    'Рекрутинг',
    'Подбор персонала',
  ),
  onboarding = term(
    'Onboarding',
    'Onboarding',
    'Onboarding',
    'Онбординг',
    'Онбординг',
    'Онбординг',
  ),
  branding = term(
    'Employer branding',
    'Employer Branding',
    'Employer branding',
    'Работодателска марка',
    'Бренд роботодавця',
    'HR-бренд',
  ),
  interviewing = term(
    'Interviewing',
    'Interviewführung',
    'Entrevistas',
    'Провеждане на интервюта',
    'Проведення співбесід',
    'Проведение собеседований',
  ),
  sourcing = term(
    'Talent sourcing',
    'Active Sourcing',
    'Búsqueda de talento',
    'Търсене на таланти',
    'Сорсинг',
    'Сорсинг',
  ),
  laborLaw = term(
    'Labor law',
    'Arbeitsrecht',
    'Derecho laboral',
    'Трудово право',
    'Трудове право',
    'Трудовое право',
  ),
  performance = term(
    'Performance management',
    'Performance-Management',
    'Gestión del desempeño',
    'Управление на представянето',
    'Управління ефективністю',
    'Управление эффективностью',
  ),
  support = term(
    'Customer support',
    'Kundensupport',
    'Atención al cliente',
    'Обслужване на клиенти',
    'Підтримка клієнтів',
    'Поддержка клиентов',
  ),
  ticketing = term(
    'Ticket systems',
    'Ticketsysteme',
    'Sistemas de tickets',
    'Тикет системи',
    'Тікет-системи',
    'Тикет-системы',
  ),
  troubleshooting = term(
    'Troubleshooting',
    'Fehlerbehebung',
    'Resolución de incidencias',
    'Отстраняване на проблеми',
    'Усунення несправностей',
    'Решение проблем',
  ),
  success = term(
    'Customer success',
    'Customer Success',
    'Customer success',
    'Клиентски успех',
    'Customer success',
    'Customer success',
  ),
  knowledge = term(
    'Knowledge base',
    'Wissensdatenbank',
    'Base de conocimiento',
    'База знания',
    'База знань',
    'База знаний',
  ),
  projects = term(
    'Project management',
    'Projektmanagement',
    'Gestión de proyectos',
    'Управление на проекти',
    'Управління проєктами',
    'Управление проектами',
  ),
  processes = term(
    'Process optimization',
    'Prozessoptimierung',
    'Optimización de procesos',
    'Оптимизация на процеси',
    'Оптимізація процесів',
    'Оптимизация процессов',
  ),
  logistics = term(
    'Logistics',
    'Logistik',
    'Logística',
    'Логистика',
    'Логістика',
    'Логистика',
  ),
  supply = term(
    'Supply chain',
    'Lieferkette',
    'Cadena de suministro',
    'Верига на доставки',
    'Ланцюг постачання',
    'Цепочки поставок',
  ),
  vendors = term(
    'Vendor management',
    'Lieferantenmanagement',
    'Gestión de proveedores',
    'Управление на доставчици',
    'Робота з постачальниками',
    'Работа с поставщиками',
  ),
  scheduling = term(
    'Scheduling',
    'Terminplanung',
    'Gestión de agendas',
    'Планиране на графици',
    'Планування графіків',
    'Планирование графиков',
  ),
  dataEntry = term(
    'Data entry',
    'Datenerfassung',
    'Entrada de datos',
    'Въвеждане на данни',
    'Введення даних',
    'Ввод данных',
  ),
  correspondence = term(
    'Business correspondence',
    'Geschäftskorrespondenz',
    'Correspondencia comercial',
    'Делова кореспонденция',
    'Ділове листування',
    'Деловая переписка',
  ),
  bookkeeping = term(
    'Bookkeeping',
    'Buchführung',
    'Teneduría de libros',
    'Книговодство',
    'Бухоблік',
    'Бухучёт',
  )

export interface SkillRole {
  id: string
  ru: string
  en: string
  /** Job-title words in any of the six languages. */
  match: RegExp
  skills: Term[]
}

// Concrete tools and methods only: the writing guide asks for skills a reader
// can check, so soft skills like “communication” are left out on purpose.
export const skillRoles: SkillRole[] = [
  {
    id: 'design',
    ru: 'Дизайн',
    en: 'Design',
    match: /design|дизайн|diseñ|ux|ui\b/i,
    skills: [
      'Figma',
      research,
      prototyping,
      designSystems,
      usability,
      wireframes,
      accessibility,
      'Adobe Illustrator',
      'Adobe Photoshop',
      'HTML / CSS',
    ],
  },
  {
    id: 'development',
    ru: 'Разработка',
    en: 'Development',
    match:
      /develop|engineer|programm|software|frontend|backend|full.?stack|devops|entwickl|ingenier|desarroll|разработ|программ|розроб|програм|инженер|інженер/i,
    skills: [
      'JavaScript',
      'TypeScript',
      'React',
      'Node.js',
      'Python',
      'SQL',
      'Git',
      'REST API',
      'Docker',
      'AWS',
      'CI/CD',
      testing,
    ],
  },
  {
    id: 'data',
    ru: 'Данные',
    en: 'Data',
    match:
      /data|analyst|analy|daten|datos|analist|данн|даних|аналит|аналіт|анализ/i,
    skills: [
      'SQL',
      'Python',
      'Excel',
      'Power BI',
      'Tableau',
      statistics,
      'A/B testing',
      dataViz,
      'pandas',
      ml,
    ],
  },
  {
    id: 'product',
    ru: 'Продукт',
    en: 'Product',
    match: /product|produkt|producto|продукт|owner/i,
    skills: [
      strategy,
      roadmap,
      research,
      'Jira',
      'Scrum',
      'A/B testing',
      analytics,
      stakeholders,
      prioritization,
      'OKR',
    ],
  },
  {
    id: 'marketing',
    ru: 'Маркетинг',
    en: 'Marketing',
    match: /market|seo|smm|content|маркет|контент/i,
    skills: [
      'SEO',
      'Google Analytics',
      'Google Ads',
      content,
      social,
      emailMarketing,
      copywriting,
      'HubSpot',
      'Meta Ads',
      automation,
    ],
  },
  {
    id: 'sales',
    ru: 'Продажи',
    en: 'Sales',
    match:
      /sales|account (manager|executive)|vertrieb|verkauf|ventas|comercial|продаж|търгов/i,
    skills: [
      'Salesforce',
      'CRM',
      leadGen,
      negotiation,
      accounts,
      b2b,
      pipeline,
      'HubSpot',
      presentations,
    ],
  },
  {
    id: 'finance',
    ru: 'Финансы',
    en: 'Finance',
    match:
      /financ|accountant|accounting|controll|buchhalt|finanz|contab|финанс|фінанс|бухгалт|счетовод|економ|эконом/i,
    skills: [
      'Excel',
      modeling,
      budgeting,
      forecasting,
      'SAP',
      'IFRS',
      accounting,
      reporting,
      controlling,
      'DATEV',
    ],
  },
  {
    id: 'hr',
    ru: 'HR',
    en: 'HR',
    match:
      /\bhr\b|recruit|talent|people|personal|recursos humanos|рекрут|персонал|кадр|подбор/i,
    skills: [
      recruiting,
      onboarding,
      branding,
      interviewing,
      sourcing,
      'LinkedIn Recruiter',
      'Workday',
      laborLaw,
      performance,
    ],
  },
  {
    id: 'support',
    ru: 'Поддержка',
    en: 'Support',
    match: /support|service|kunden|soporte|atención|поддерж|підтрим|обслуж/i,
    skills: [
      support,
      'Zendesk',
      ticketing,
      'CRM',
      troubleshooting,
      success,
      knowledge,
      'Salesforce',
    ],
  },
  {
    id: 'operations',
    ru: 'Операции',
    en: 'Operations',
    match:
      /operat|project|logist|supply|projekt|proyect|операц|проект|проєкт|логист|логіст/i,
    skills: [
      projects,
      processes,
      logistics,
      supply,
      'SAP',
      'Excel',
      'Lean',
      'Scrum',
      vendors,
      'MS Project',
    ],
  },
  {
    id: 'office',
    ru: 'Офис',
    en: 'Office',
    match:
      /assist|office|admin|secretar|büro|sekretär|asistente|ассистент|асистент|офис|офіс|секретар/i,
    skills: [
      'Microsoft Office',
      'Excel',
      'PowerPoint',
      'Google Workspace',
      scheduling,
      dataEntry,
      correspondence,
      bookkeeping,
    ],
  },
]

export const skillText = (skill: Term, lang: Locale) =>
  typeof skill === 'string' ? skill : skill[lang]

/** The field that the job title points to, if any. */
export const roleFor = (jobTitle: string) =>
  jobTitle.trim()
    ? skillRoles.find((role) => role.match.test(jobTitle))
    : undefined

/** ISO 639-1 codes for the language picker; names come from the browser in the resume language. */
export const languageCodes = [
  'en',
  'de',
  'fr',
  'es',
  'it',
  'pt',
  'nl',
  'pl',
  'uk',
  'ru',
  'bg',
  'cs',
  'sk',
  'ro',
  'hu',
  'el',
  'tr',
  'sv',
  'da',
  'nb',
  'fi',
  'et',
  'lv',
  'lt',
  'sr',
  'hr',
  'sl',
  'sq',
  'mk',
  'be',
  'ka',
  'hy',
  'az',
  'kk',
  'uz',
  'he',
  'ar',
  'fa',
  'hi',
  'ur',
  'bn',
  'zh',
  'ja',
  'ko',
  'vi',
  'th',
  'id',
  'ms',
  'tl',
  'sw',
  'ca',
  'is',
] as const

const capitalize = (text: string, lang: Locale) =>
  text.charAt(0).toLocaleUpperCase(lang) + text.slice(1)

/** “German” in the resume language: “Deutsch”, “Немецкий”, “Alemán”… */
export function languageName(code: string, lang: Locale) {
  try {
    const name = new Intl.DisplayNames([lang], { type: 'language' }).of(code)
    return name && name !== code ? capitalize(name, lang) : code
  } catch {
    return code
  }
}

/** CEFR levels with the wording used in the sample resumes. */
export const proficiency: Record<Locale, string[]> = {
  en: [
    'Native',
    'C2 — proficient',
    'C1 — advanced',
    'B2 — upper intermediate',
    'B1 — intermediate',
    'A2 — elementary',
    'A1 — beginner',
  ],
  de: [
    'Muttersprache',
    'C2 — verhandlungssicher',
    'C1 — fortgeschritten',
    'B2 — gute Kenntnisse',
    'B1 — Mittelstufe',
    'A2 — Grundkenntnisse',
    'A1 — Anfänger',
  ],
  es: [
    'Nativo',
    'C2 — dominio',
    'C1 — avanzado',
    'B2 — intermedio alto',
    'B1 — intermedio',
    'A2 — básico',
    'A1 — principiante',
  ],
  bg: [
    'Майчин',
    'C2 — свободно владеене',
    'C1 — напреднал',
    'B2 — горно средно',
    'B1 — средно',
    'A2 — основно',
    'A1 — начинаещ',
  ],
  uk: [
    'Рідна',
    'C2 — вільне володіння',
    'C1 — просунутий',
    'B2 — вище середнього',
    'B1 — середній',
    'A2 — елементарний',
    'A1 — початковий',
  ],
  ru: [
    'Родной',
    'C2 — в совершенстве',
    'C1 — продвинутый',
    'B2 — выше среднего',
    'B1 — средний',
    'A2 — элементарный',
    'A1 — начальный',
  ],
}
/** Short chip label: “Native” stays a word, the rest show the CEFR code. */
export const proficiencyShort = (level: string) =>
  /^[ABC][12]\b/.test(level) ? level.slice(0, 2) : level
